/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertemuan2_latiahan5_kelompok1;

/**
 *
 * @author USER
 */
public class pertemuan2_latihan5_kelompok1 extends javax.swing.JFrame {

    /**
     * Creates new form pertemuan2_latihan5_kelompok1
     */
    public pertemuan2_latihan5_kelompok1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenis_kelamin = new javax.swing.ButtonGroup();
        agama = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        text1_kelompok1 = new javax.swing.JLabel();
        jTextField1_kelompok1 = new javax.swing.JTextField();
        text2_kelompok1 = new javax.swing.JLabel();
        jRadioButton1_kelompok1 = new javax.swing.JRadioButton();
        jRadioButton2_kelompok1 = new javax.swing.JRadioButton();
        text2_kelompok2 = new javax.swing.JLabel();
        jRadioButton3_kelompok1 = new javax.swing.JRadioButton();
        jRadioButton4_kelompok1 = new javax.swing.JRadioButton();
        jRadioButton5_kelompok1 = new javax.swing.JRadioButton();
        jRadioButton6_kelompok1 = new javax.swing.JRadioButton();
        jRadioButton7_kelmpok1 = new javax.swing.JRadioButton();
        text2_kelompok3 = new javax.swing.JLabel();
        jCheckBox1_kelompok1 = new javax.swing.JCheckBox();
        jCheckBox2_kelompok1 = new javax.swing.JCheckBox();
        jCheckBox3_kelompok3 = new javax.swing.JCheckBox();
        jButton1_kelompok1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1_kelompok1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text1_kelompok1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        text1_kelompok1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1_kelompok1.setText("NAMA");

        jTextField1_kelompok1.setText("Masukkan Nama");
        jTextField1_kelompok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_kelompok1ActionPerformed(evt);
            }
        });

        text2_kelompok1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        text2_kelompok1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text2_kelompok1.setText("JENIS KELAMIN");

        jenis_kelamin.add(jRadioButton1_kelompok1);
        jRadioButton1_kelompok1.setText("Laki-laki");
        jRadioButton1_kelompok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_kelompok1ActionPerformed(evt);
            }
        });

        jenis_kelamin.add(jRadioButton2_kelompok1);
        jRadioButton2_kelompok1.setText("Perempuan");
        jRadioButton2_kelompok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_kelompok1ActionPerformed(evt);
            }
        });

        text2_kelompok2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        text2_kelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text2_kelompok2.setText("AGAMA");

        agama.add(jRadioButton3_kelompok1);
        jRadioButton3_kelompok1.setText("Islam");
        jRadioButton3_kelompok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3_kelompok1ActionPerformed(evt);
            }
        });

        agama.add(jRadioButton4_kelompok1);
        jRadioButton4_kelompok1.setText("Kristen");

        agama.add(jRadioButton5_kelompok1);
        jRadioButton5_kelompok1.setText("Hindu");

        agama.add(jRadioButton6_kelompok1);
        jRadioButton6_kelompok1.setText("Buddha");

        agama.add(jRadioButton7_kelmpok1);
        jRadioButton7_kelmpok1.setText("Konghuchu");

        text2_kelompok3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        text2_kelompok3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text2_kelompok3.setText("HOBBY");

        jCheckBox1_kelompok1.setText("Berenang");
        jCheckBox1_kelompok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_kelompok1ActionPerformed(evt);
            }
        });

        jCheckBox2_kelompok1.setText("Volley");

        jCheckBox3_kelompok3.setText("Bulu Tangkis");

        jButton1_kelompok1.setText("PROSES");
        jButton1_kelompok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_kelompok1ActionPerformed(evt);
            }
        });

        jTextArea1_kelompok1.setColumns(20);
        jTextArea1_kelompok1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1_kelompok1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text1_kelompok1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jTextField1_kelompok1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(text2_kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton3_kelompok1))
                                    .addComponent(text2_kelompok1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(text2_kelompok3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox1_kelompok1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton1_kelompok1)
                                            .addComponent(jRadioButton4_kelompok1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jRadioButton2_kelompok1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton5_kelompok1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton6_kelompok1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton7_kelmpok1))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBox2_kelompok1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox3_kelompok3))
                                    .addComponent(jButton1_kelompok1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text1_kelompok1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_kelompok1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2_kelompok1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1_kelompok1)
                    .addComponent(jRadioButton2_kelompok1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2_kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3_kelompok1)
                    .addComponent(jRadioButton4_kelompok1)
                    .addComponent(jRadioButton5_kelompok1)
                    .addComponent(jRadioButton6_kelompok1)
                    .addComponent(jRadioButton7_kelmpok1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2_kelompok3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1_kelompok1)
                    .addComponent(jCheckBox2_kelompok1)
                    .addComponent(jCheckBox3_kelompok3))
                .addGap(18, 18, 18)
                .addComponent(jButton1_kelompok1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_kelompok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_kelompok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_kelompok1ActionPerformed

    private void jRadioButton1_kelompok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_kelompok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1_kelompok1ActionPerformed

    private void jRadioButton2_kelompok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_kelompok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2_kelompok1ActionPerformed

    private void jRadioButton3_kelompok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3_kelompok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3_kelompok1ActionPerformed

    private void jCheckBox1_kelompok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_kelompok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1_kelompok1ActionPerformed

    private void jButton1_kelompok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_kelompok1ActionPerformed
        /*
        Nama : Dimas Aryasatya
        NPM : 21552011325
        Kelas :TIFRM21
        KELOMPOK : 1
        GITHUB : daryassatya
        */

        // Area Logic Dari Field Input Nama
        jTextArea1_kelompok1.setText("");
        String getText = jTextField1_kelompok1.getText();
        jTextArea1_kelompok1.append("Nama : " + getText + "\n");
        
        // Area Logic Dari SelctionBox Jenis Kelamin
        String jenisKelaminSelected;
        if(jRadioButton1_kelompok1.isSelected()) {
            jenisKelaminSelected = jRadioButton1_kelompok1.getText();
        } else if(jRadioButton2_kelompok1.isSelected()) {
            jenisKelaminSelected = jRadioButton2_kelompok1.getText();
        } else {
            jenisKelaminSelected = "Belum Memilih Jenis Kelamin!";
        }
        jTextArea1_kelompok1.append("Jenis Kelamin : " + jenisKelaminSelected + "\n");
        
       // Area Logic Dari SelectionBox Agama
       String agamaSelected;
       if(jRadioButton3_kelompok1.isSelected()) {
            agamaSelected = jRadioButton3_kelompok1.getText();
        } else if(jRadioButton4_kelompok1.isSelected()) {
            agamaSelected = jRadioButton4_kelompok1.getText();
        } else if(jRadioButton5_kelompok1.isSelected()) {
            agamaSelected = jRadioButton5_kelompok1.getText();
        } else if(jRadioButton6_kelompok1 .isSelected()) {
            agamaSelected = jRadioButton7_kelmpok1  .getText();
        } else if(jRadioButton6_kelompok1 .isSelected()) {
            agamaSelected = jRadioButton7_kelmpok1  .getText();
        } else {
            agamaSelected = "Belum Memilih Agama!";
        }
        jTextArea1_kelompok1.append("Agama : " + agamaSelected + "\n");
         
         
        // Area Logic Dari CheckBox Hobby
        String hobby="";
        if (jCheckBox1_kelompok1.isSelected()){
            hobby += jCheckBox1_kelompok1.getText();
        } 
        if (jCheckBox2_kelompok1.isSelected()){
            hobby += " ," + jCheckBox2_kelompok1.getText();
        } 
        if (jCheckBox3_kelompok3.isSelected()){
            hobby += " ," + jCheckBox3_kelompok3.getText();
        }
        jTextArea1_kelompok1.append("Hobby : " + hobby + "\n");
        
        
        
    }//GEN-LAST:event_jButton1_kelompok1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pertemuan2_latihan5_kelompok1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pertemuan2_latihan5_kelompok1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pertemuan2_latihan5_kelompok1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pertemuan2_latihan5_kelompok1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pertemuan2_latihan5_kelompok1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup agama;
    private javax.swing.JButton jButton1_kelompok1;
    private javax.swing.JCheckBox jCheckBox1_kelompok1;
    private javax.swing.JCheckBox jCheckBox2_kelompok1;
    private javax.swing.JCheckBox jCheckBox3_kelompok3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1_kelompok1;
    private javax.swing.JRadioButton jRadioButton2_kelompok1;
    private javax.swing.JRadioButton jRadioButton3_kelompok1;
    private javax.swing.JRadioButton jRadioButton4_kelompok1;
    private javax.swing.JRadioButton jRadioButton5_kelompok1;
    private javax.swing.JRadioButton jRadioButton6_kelompok1;
    private javax.swing.JRadioButton jRadioButton7_kelmpok1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1_kelompok1;
    private javax.swing.JTextField jTextField1_kelompok1;
    private javax.swing.ButtonGroup jenis_kelamin;
    private javax.swing.JLabel text1_kelompok1;
    private javax.swing.JLabel text2_kelompok1;
    private javax.swing.JLabel text2_kelompok2;
    private javax.swing.JLabel text2_kelompok3;
    // End of variables declaration//GEN-END:variables
}
